name: "GRES B2B Governance"
description: "Run GRES B2B governance verification with cap-aware threshold gating. Free to use - no license key required."
author: "GRES Digital"

branding:
  icon: "shield"
  color: "blue"

inputs:
  # === Mode ===
  mode:
    description: "Operation mode: verify | watch | shadow"
    required: false
    default: "verify"

  # === Configuration ===
  config:
    description: "Path to custom config file (e.g. .b2b/policy.yml)"
    required: false
    default: ""

  # === Strictness ===
  fail_on_red:
    description: "If set (true/false), writes fail_on_red in .b2b/config.yml"
    required: false
    default: ""

  allow_amber:
    description: "If set (true/false), writes allow_amber in .b2b/config.yml"
    required: false
    default: ""

  # === Shadow mode ===
  vectors:
    description: "Path to shadow vectors.yml (required when mode=shadow)"
    required: false
    default: ""

  # === Output paths ===
  sarif:
    description: "Path for SARIF output file"
    required: false
    default: ".b2b/results.sarif"

  junit:
    description: "Path for JUnit XML output file"
    required: false
    default: ".b2b/junit.xml"

  # === Release settings ===
  version:
    description: "Release tag to install (e.g. v4.0.0). Use 'latest' for newest release."
    required: false
    default: "latest"

  repo:
    description: "Repository hosting gres-b2b releases (owner/name)"
    required: false
    default: "ajranjith/b2b-governance-action"

  token:
    description: "GitHub token for downloading releases (use secrets.GITHUB_TOKEN for private repos)"
    required: false
    default: ""

outputs:
  certificate:
    description: "Path to verification certificate"
    value: ".b2b/certificate.json"
  sarif:
    description: "Path to SARIF report"
    value: ${{ inputs.sarif }}
  junit:
    description: "Path to JUnit report"
    value: ${{ inputs.junit }}
  report:
    description: "Path to JSON report"
    value: ".b2b/report.json"
  html:
    description: "Path to HTML dashboard"
    value: ".b2b/report.html"

runs:
  using: "composite"
  steps:
    - name: Install and run gres-b2b
      shell: bash
      env:
        GRES_B2B_MODE: ${{ inputs.mode }}
        GRES_B2B_CONFIG: ${{ inputs.config }}
        GRES_B2B_FAIL_ON_RED: ${{ inputs.fail_on_red }}
        GRES_B2B_ALLOW_AMBER: ${{ inputs.allow_amber }}
        GRES_B2B_VECTORS: ${{ inputs.vectors }}
        GRES_B2B_SARIF: ${{ inputs.sarif }}
        GRES_B2B_JUNIT: ${{ inputs.junit }}
        GRES_B2B_VERSION: ${{ inputs.version }}
        GRES_B2B_REPO: ${{ inputs.repo }}
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        set -euo pipefail
        bash "${{ github.action_path }}/scripts/install-and-run.sh"
